### ISSUE TITLE
这么辣鸡的吗？不支持自定义布局？

### ISSUE THREAD

**Issue by q88qaz** [mtjsoft/GridPager#10]
不支持自定义布局？

**Comment by mtjsoft** [comment]
> 不支持自定义布局？

能力一般，水平有限，我是Android开发的小学生，我是mtjsoft。希望您能分享一个支持自定义布局的给大家，谢谢您。

**Comment by liyujiang-gzu** [comment]
> 不支持自定义布局？

最烦这种伸手党喷子，不知道感恩。你觉得垃圾你干嘛来用？你厉害你干嘛比贡献代码改进一下？
