### ISSUE TITLE
gridpager_item.xml里为嘛要设置pdding为-10dp呢

### ISSUE THREAD

**Issue by liyujiang-gzu** [mtjsoft/GridPager#11]
`android:padding="-10dp"`会导致item文字两边被挡住：
![image](https://user-images.githubusercontent.com/16816717/86733977-36fc7a00-c064-11ea-9c65-6cf245ee3822.png)

```xml
android:padding="-10dp"
```

**Comment by mtjsoft** [comment]
当时是想除去TextView自带的内边距的，效果不是很好，后头我先把他去掉

**Comment by mtjsoft** [comment]
> `android:padding="-10dp"`会导致item文字两边被挡住：
> ![image](https://user-images.githubusercontent.com/16816717/86733977-36fc7a00-c064-11ea-9c65-6cf245ee3822.png)
> 
> ```
> android:padding="-10dp"
> ```

当时是想除去TextView自带的内边距的，效果一直不是很好，后面我先去掉

**Comment by liyujiang-gzu** [comment]
TextView自带的内边距和字体有关，可以试试`android:includeFontPadding`，如全局主题配置加入`<item name="android:includeFontPadding">false</item>`

**Comment by mtjsoft** [comment]
> TextView自带的内边距和字体有关，可以试试`android:includeFontPadding`，如全局主题配置加入`<item name="android:includeFontPadding">false</item>`

这个属性已经在3.2.0中加了，并去掉了 padding
