### ISSUE TITLE
当我设置2行4个，数据只有4个，下面的point还会显示

### ISSUE THREAD

**Issue by itkun2013** [mtjsoft/GridPager#12]
怎么操作才不会显示出来

**Comment by mtjsoft** [comment]
> 怎么操作才不会显示出来

贴一下你设置的代码

**Comment by itkun2013** [comment]
我通过数据来显示指示器
 List<AppItemEntity> realList = new ArrayList<>();
        AppItemEntity itemEntity = new AppItemEntity();
        itemEntity.setName(getString(R.string.home_app_all));
        itemEntity.setTagId(ALL_APP); //人为设置
        if (list != null && list.size() > 0) {
            realList.addAll(list);
            realList.add(itemEntity);
        } else {
            realList.add(itemEntity);
        }
        if (realList.size() <= 8) {
            //隐藏point
            AndSelectCircleView point = fragmentHomeBinding.homeGridpager.findViewById(R.id.scv);
            point.setVisibility(View.GONE);
        } else {
            AndSelectCircleView point = fragmentHomeBinding.homeGridpager.findViewById(R.id.scv);
            point.setVisibility(View.VISIBLE);
        }
        但是数据很少，不显示，数据多了，显示，不会默认选中一个，除非滑动才会选中
