### ISSUE TITLE
发现一bug

### ISSUE THREAD

**Issue by itkun2013** [mtjsoft/GridPager#14]
if (realList.size() <= 8) {
            //隐藏point
            AndSelectCircleView point = fragmentHomeBinding.homeGridpager.findViewById(R.id.scv);
            point.setVisibility(View.GONE);
        } else {
            AndSelectCircleView point = fragmentHomeBinding.homeGridpager.findViewById(R.id.scv);
            point.setVisibility(View.VISIBLE);
        }
如果首次进来数据不足2页，设置不显示point指示器，当数据刷新后，达到2页数据，piont显示，但是没有默认选择一个，用 point.setSelectPosition(0);后发现，数据全部消失了。。。

**Comment by mtjsoft** [comment]
> if (realList.size() <= 8) {
> //隐藏point
> AndSelectCircleView point = fragmentHomeBinding.homeGridpager.findViewById(R.id.scv);
> point.setVisibility(View.GONE);
> } else {
> AndSelectCircleView point = fragmentHomeBinding.homeGridpager.findViewById(R.id.scv);
> point.setVisibility(View.VISIBLE);
> }
> 如果首次进来数据不足2页，设置不显示point指示器，当数据刷新后，达到2页数据，piont显示，但是没有默认选择一个，用 point.setSelectPosition(0);后发现，数据全部消失了。。。

嗯，周末我看一下

**Comment by mtjsoft** [comment]
> if (realList.size() <= 8) {
> //隐藏point
> AndSelectCircleView point = fragmentHomeBinding.homeGridpager.findViewById(R.id.scv);
> point.setVisibility(View.GONE);
> } else {
> AndSelectCircleView point = fragmentHomeBinding.homeGridpager.findViewById(R.id.scv);
> point.setVisibility(View.VISIBLE);
> }
> 如果首次进来数据不足2页，设置不显示point指示器，当数据刷新后，达到2页数据，piont显示，但是没有默认选择一个，用 point.setSelectPosition(0);后发现，数据全部消失了。。。

下个版本会修复，并增加翻页动画效果

**Comment by mtjsoft** [comment]
> if (realList.size() <= 8) {
> //隐藏point
> AndSelectCircleView point = fragmentHomeBinding.homeGridpager.findViewById(R.id.scv);
> point.setVisibility(View.GONE);
> } else {
> AndSelectCircleView point = fragmentHomeBinding.homeGridpager.findViewById(R.id.scv);
> point.setVisibility(View.VISIBLE);
> }
> 如果首次进来数据不足2页，设置不显示point指示器，当数据刷新后，达到2页数据，piont显示，但是没有默认选择一个，用 point.setSelectPosition(0);后发现，数据全部消失了。。。

3.4.0已修复
