### ISSUE TITLE
连续点击 position 错乱问题

### ISSUE THREAD

**Issue by wenge1215** [mtjsoft/GridPager#16]
版本号：3.4.0
复现步骤：1.setCoverPageTransformer（）
                   2.row_count="2"
                   3.column_count="4"
满足上面条件后，连续点击某一个item，就会出现position错乱问题

**Comment by mtjsoft** [comment]
> 版本号：3.4.0
> 复现步骤：1.setCoverPageTransformer（）
> 2.row_count="2"
> 3.column_count="4"
> 满足上面条件后，连续点击某一个item，就会出现position错乱问题

这个问题在 3.5.0已修复
