### ISSUE TITLE
进入页面切换控制台报错

### ISSUE THREAD

**Issue by fancyvip** [mtjsoft/GridPager#20]
切换页面之后报 E/RecyclerView: No adapter attached; skipping [layout错误，每次都能复现]
![image](https://user-images.githubusercontent.com/23178419/97946200-a8ef9080-1dc4-11eb-948e-d61da56e320b.png)

**Comment by mtjsoft** [comment]
> 切换页面之后报 E/RecyclerView: No adapter attached; skipping [layout错误，每次都能复现]
> ![image](https://user-images.githubusercontent.com/23178419/97946200-a8ef9080-1dc4-11eb-948e-d61da56e320b.png)

哪个版本的？用最新的版本试试

**Comment by fancyvip** [comment]
> > E / RecyclerView：未连接适配器；跳过[layout错误，每次都能复现]
> > ![图片](https://user-images.githubusercontent.com/23178419/97946200-a8ef9080-1dc4-11eb-948e-d61da56e320b.png)
> 
> 哪个版本的？用最新的版本试试

是最新版的3.6，点击最下方两个测试按钮切换之后便会出现该错误，在我自己的项目中切换tabbar后依旧会报该错误
![image](https://user-images.githubusercontent.com/23178419/97948050-47322500-1dca-11eb-9fc3-3fd7ba504463.png)

**Comment by mtjsoft** [comment]
> > > E / RecyclerView：未连接适配器；跳过[layout错误，每次都能复现]
> > > ![图片](https://user-images.githubusercontent.com/23178419/97946200-a8ef9080-1dc4-11eb-948e-d61da56e320b.png)
> > 
> > 
> > 哪个版本的？用最新的版本试试
> 
> 是最新版的3.6，点击最下方两个测试按钮切换之后便会出现该错误，在我自己的项目中切换tabbar后依旧会报该错误
> ![image](https://user-images.githubusercontent.com/23178419/97948050-47322500-1dca-11eb-9fc3-3fd7ba504463.png)

在View.post()获取到实际宽度之后才设置的 Adapter，所以有这个错误提示。不影响使用。你可以把设置 Adapter 拿到View.post()的前面，等拿到实际的宽度后，再执行notifyDataSetChanged()。就不会提示了。
