### ISSUE TITLE
项目使用在表情栏中实现的一个问题

### ISSUE THREAD

**Issue by fankes** [mtjsoft/GridPager#23]
在设置行数和列数
`setCount
setColumnCount`
后，我发现貌似行间距是平均分配进行补全的，但是这个里面就存在一个问题
如果最后一页只有两行，那么这个行间距平均分配就会出问题
解决方案：根据行数和 View 实际高度决定行间距是平均分配还是使用默认值
可以加一个 setColumnDefaultHeight 参数
问题截图：
<img width="381" alt="QQ20210324-042904@2x" src="https://user-images.githubusercontent.com/37344460/112213845-7a7e2f00-8c59-11eb-8956-7441d876fcad.png">

**Comment by mtjsoft** [comment]
> 在设置行数和列数
> `setCount setColumnCount`
> 后，我发现貌似行间距是平均分配进行补全的，但是这个里面就存在一个问题
> 如果最后一页只有两行，那么这个行间距平均分配就会出问题
> 解决方案：根据行数和 View 实际高度决定行间距是平均分配还是使用默认值
> 可以加一个 setColumnDefaultHeight 参数
> 问题截图：
> <img alt="QQ20210324-042904@2x" width="381" src="https://user-images.githubusercontent.com/37344460/112213845-7a7e2f00-8c59-11eb-8956-7441d876fcad.png">

在3.7.0版本，新增了对齐方式设置方法，以及是否需要显示文本属性
