### ISSUE TITLE
发现几个问题

### ISSUE THREAD

**Issue by taoczZYC** [mtjsoft/GridPager#3]
实际使用发现设置文字大小的属性text_size没用，不管设置多少字体都会很大，不知道是为什么，然后viewpager的scrollbars会显示出来，建议去掉；然后初始化控件后，指示器只会在第一次默认选中0，刷新数据后默认选中消失了，按截图中修改后好了，另外建议加一个指示器与viewpager的间距属性
![WeChat8e601884624a0393a2c777fefbdf536c](https://user-images.githubusercontent.com/11548042/64577792-05694280-d3b0-11e9-8f41-ca6f686acbe3.png)

**Comment by mtjsoft** [comment]
> 实际使用发现设置文字大小的属性text_size没用，不管设置多少字体都会很大，不知道是为什么，然后viewpager的scrollbars会显示出来，建议去掉；然后初始化控件后，指示器只会在第一次默认选中0，刷新数据后默认选中消失了，按截图中修改后好了，另外建议加一个指示器与viewpager的间距属性
> ![WeChat8e601884624a0393a2c777fefbdf536c](https://user-images.githubusercontent.com/11548042/64577792-05694280-d3b0-11e9-8f41-ca6f686acbe3.png)

已在v1.2.0中修复，并添加了新的属性
