### ISSUE TITLE
只适用本地指定数据，不适用网络动态获取填充，没有提供数据刷新方案

### ISSUE THREAD

**Issue by shangjin-Li** [mtjsoft/GridPager#5]

**Comment by mtjsoft** [comment]
在绑定数据的地方，通过position从数据源list获取对应的值去设置，例如 String **icon**  = list.get(**position**).getIcon(); 至于这个list是本地数据，还是网络数据，没什么不一样吧。网络图片，根据自己的图片加载框架设置就好啦，例如 Glide....load( **icon** ).....(**imagevie**);

**Comment by mtjsoft** [comment]
下个版本计划提供整体数据刷新，指定第几页数据刷新。
