### ISSUE TITLE
父布局 不能有margin 会显示不全

### ISSUE THREAD

**Issue by YUHAN-GUO** [mtjsoft/GridPager#8]

**Comment by taoczZYC** [comment]
![WeChat554c192c0d93267065db8643a46d14d2](https://user-images.githubusercontent.com/11548042/78769643-31898800-79c0-11ea-8ad2-26b67d4aeb02.png)
计算子view宽度时作者取了屏幕宽度，其实应该取控件本身宽度，望修复 @mtjsoft
